export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  UNAUTHORIZED: "UNAUTHORIZED",
  VENUE_NOT_FOUND: "VENUE_NOT_FOUND",
  SLUG_TAKEN: "SLUG_TAKEN",
  SLUG_RESERVED: "SLUG_RESERVED",
  CATEGORY_NOT_EMPTY: "CATEGORY_NOT_EMPTY",
  CATEGORY_NOT_FOUND: "CATEGORY_NOT_FOUND",
  ITEM_NOT_FOUND: "ITEM_NOT_FOUND",
  ORDER_NOT_FOUND: "ORDER_NOT_FOUND",
  TABLE_NOT_FOUND: "TABLE_NOT_FOUND",
  TABLE_LIMIT: "TABLE_LIMIT",
  TABLE_LABEL_TAKEN: "TABLE_LABEL_TAKEN",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
